export const SEARCH_SONG_REQUEST= '/search/SEARCH_SONG_REQUEST'
export const SEARCH_HOT_REQUEST = '/search/SEARCH_HOT_REQUEST'
export const SEARCH_DEFAULT_REQUEST = '/search/SEARCH_DEFAULT_REQUEST'
export const SEARCH_SUGGEST_REQUEST = '/search/SEARCH_SUGGEST_REQUEST'